//ESTADO PARA LOS LIBROS
export const OBTENER_LIBROS_EXITO = 'OBTENER_PRODUCTOS_EXITO';


//ESTADO PARA LOS PEDIDOS
export const SELECCIONAR_LIBROS = 'SELECCIONAR_LIBROS';

//GUARDAR PEDIDO
export const GUARGAR_PEDIDO = 'GUARGAR_PEDIDO';

//PRESTAR LIBRO
export const PRESTAR_LIBRO = 'PRESTAR_LIBRO';

//OBTENER LIBROS PRESTADOS
export const OBTENER_LIBROS_PRESTADOS = 'OBTENER_LIBROS_PRESTADOS'

//DEVOLUCION LIBRO
export const DEVOLVER_LIBRO = 'DEVOLVER_LIBRO' 

//ELIMINAR LIBRO
export const ELIMINAR_LIBRO = 'ELIMINAR_LIBRO'