//ESTADO PARA LOS LIBROS
export const OBTENER_LIBROS_EXITO = 'OBTENER_PRODUCTOS_EXITO';


//ESTADO PARA LOS PEDIDOS
export const SELECCIONAR_LIBROS = 'SELECCIONAR_LIBROS';

//GUARDAR PEDIDO
export const GUARGAR_PEDIDO = 'GUARGAR_PEDIDO';
